#!/bin/bash

# ref: CUI超お手軽英語辞書 - capriccioso String Creating(Object something){ return My.Expression(something); } (http://d.hatena.ne.jp/its_out_of_tune/20120610/1339311044)
# + メモ化 & 言及英単語を再帰的呼び出し

WEBLIO="http://ejje.weblio.jp/content/$1"
TMP="/tmp/cuijaegdect.html"
DICT_FILENAME="$HOME/Dropbox/dict.txt"

if [ ! -e $DICT_FILENAME ]; then
  touch $DICT_FILENAME
fi

AG=$(ag "^$1の意味や和訳|^$1を英語に訳すと" $DICT_FILENAME)
OUTPUT=""

if [ -z "$AG" ]; then
  curl -s $WEBLIO > $TMP
  OUTPUT=$(ag --no-numbers 'name="description"' $TMP | sed -e 's/<meta name="description" content="\([^"]*\)\-.*$/\1/')
  # 調べた結果を辞書に書き出す
  echo $OUTPUT >> $DICT_FILENAME
else
  OUTPUT=$AG
fi

echo $OUTPUT
# →の後に他の英単語を示して終わり(例. ranの意味や和訳。 【動詞】 →run の過去形.)という事があるので(参照してるのに→が無い場合や→があっても単語の参照でない場合とかもあるけど)、そういう場合には参照された他の英単語を再びこのコマンドに掛けるようにする
case $OUTPUT in
  *→*)
    je `echo $OUTPUT | sed -e "s/^.*→\([^ ]*\).*$/\1/"`;;
  *を参照*)
    je `echo $OUTPUT | sed -e "s/^.*印欧語根などは\([^\<]*\)を参照.*$/\1/"`;;
esac
