#!/bin/bash

# ref: CUI超お手軽英語辞書 - capriccioso String Creating(Object something){ return My.Expression(something); } (http://d.hatena.ne.jp/its_out_of_tune/20120610/1339311044)
# + メモ化 & 言及英単語を再帰的呼び出し

WEBLIO="http://ejje.weblio.jp/content/$1"
DICT="$HOME/Dropbox/dict.txt"

if [ ! -e $DICT ]; then
  touch $DICT
fi

AG=$(ag "^$1の意味や和訳|^$1を英語に訳すと" $DICT)
OUTPUT=""

if [ -z "$AG" ]; then
  OUTPUT=$(curl -s $WEBLIO | ag --no-numbers 'name="description"' | sed -e 's/<meta name="description" content="\([^"]*\)\-.*$/\1/')
  # 調べた結果を辞書に書き出す
  echo $OUTPUT >> $DICT
else
  OUTPUT=$AG
fi

echo $OUTPUT

case $OUTPUT in
  *→*\ の過去形\.*)
    je `echo $OUTPUT | sed -e "s/^.*→\([^\ ]*\)\ の過去形\..*$/\1/"`;;
  *を参照*)
    je `echo $OUTPUT | sed -e "s/^.*印欧語根などは\([^ ]*\)を参照.*$/\1/"`;;
  *Plural\ form\ of\ *.)
    je `echo $OUTPUT | sed -e "s/^.*Plural\ form\ of\ \([^\ ]*\)\..*$/\1/"`;;
esac
